logging:
  level:
    org.springframework.web: WARN
    com.ote.test: INFO

server:
  port: ${PORT:8081}
  session.timeout: 1
  connection-timeout : 100

spring:
  application:
    name: proxy-service

endpoints:
  health:
    enabled: true
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

dataservice.uri: http://localhost:8083

redis:
  host: localhost
  port: 6379
