server:
  port: ${PORT:8080}

spring:
  application:
    name: client
  boot:
    admin:
      url: http://localhost:8080

endpoints:
  health:
    enabled: true
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

proxy-service:
  ribbon:
    eureka.enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

management:
  security:
    enabled: false